/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#define RCC_AHB1ENR *((uint32_t *)0x40023830)
#define GPIOD_MODER *((uint32_t *)0x40020c00)
#define GPIOD_ODR   *((uint32_t *)0x40020c14)

void init_leds()
{
	RCC_AHB1ENR |= 1<< 3;
	GPIOD_MODER |= 1<<24;
	GPIOD_MODER |= 1<<28;

}

void turn_green_on()
{
	GPIOD_ODR   |= 1<<12;
}


void turn_red_on()
{
	GPIOD_ODR   |= 1<<14;
}


void turn_green_off()
{
	GPIOD_ODR   &= ~(1<<12);
}

void turn_red_off()
{
	GPIOD_ODR   &= ~(1<<14);
}

void delay(uint32_t time)
{
	while(time--);
}

int main(void)
{

	init_leds();

	for(int i=0; i < 10; i++)
	{
		turn_green_on();
		delay(40000000);
		turn_green_off();
		delay(40000000);

	}


	for(int j=0; j < 4; j++)
	{
		turn_red_on();
		delay(40000000);
		turn_red_off();
		delay(40000000);

	}



	/* Loop forever */
	for(;;);

}
